### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by marklawlor** [marklawlor/expo-cli#1]
- [x] Updated dependencies
- [x] Ignore initial errors
- [x] Create "base" project with react-native-web working with all expo features removed
- [ ] Enable expo's aliasing
- [ ] Enable expo's env loading
- [ ] Enable resize observer polyfill
- [ ] Enable the expo babel plugin
- [ ] Add the expo babel loader, with all rules turned off

From here need to decide the order of things

- [ ] Babel loaders
- [ ] Enable font loading
- [ ] Enable expo's transpilation of modules
- [ ] Enable html-loader
- [ ] 
- [ ] Go back and fix types that we cast to "any"

**Comment by marklawlor** [comment]
Updated all packages. These are current errors

```
src/addons/withEntry.ts:35:3 - error TS2322: Type '() => Promise<Entry>' is not assignable to type 'string | stri
ng[] | EntryObject | (() => string | string[] | EntryObject | Promise<EntryStatic>) | undefined'.
  Type '() => Promise<Entry>' is not assignable to type '() => string | string[] | EntryObject | Promise<EntrySta
tic>'.
    Type 'Promise<Entry>' is not assignable to type 'string | string[] | EntryObject | Promise<EntryStatic>'.
      Type 'Promise<Entry>' is not assignable to type 'Promise<EntryStatic>'.
        Type 'Entry' is not assignable to type 'EntryStatic'.
          Type '() => string | string[] | EntryObject | Promise<EntryStatic>' is not assignable to type 'EntrySta
tic'.
            Type '() => string | string[] | EntryObject | Promise<EntryStatic>' is missing the following properti
es from type 'string[]': pop, push, concat, join, and 25 more.

35   webpackConfig.entry = async () => {
     ~~~~~~~~~~~~~~~~~~~

src/addons/withEntry.ts:37:17 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

37     if (entries.app) {
                   ~~~

src/addons/withEntry.ts:38:20 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

38       if (!entries.app.includes(extraAppEntry)) {
                      ~~~

src/addons/withEntry.ts:39:36 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

39         if (!Array.isArray(entries.app)) {
                                      ~~~

src/addons/withEntry.ts:40:19 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

40           entries.app = [entries.app];
                     ~~~

src/addons/withEntry.ts:40:34 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

40           entries.app = [entries.app];
                                    ~~~

src/addons/withEntry.ts:42:17 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

42         entries.app.unshift(extraAppEntry);
                   ~~~

src/addons/withNodeMocks.ts:19:5 - error TS2322: Type '{ __dirname?: boolean | "mock" | "eval-only" | undefined;
__filename?: boolean | "mock" | "eval-only" | undefined; global?: boolean | undefined; module: string; dgram: str
ing; dns: string; ... 4 more ...; child_process: string; }' is not assignable to type 'false | NodeOptions | unde
fined'.
  Object literal may only specify known properties, and 'module' does not exist in type 'NodeOptions'.

19     module: 'empty',
       ~~~~~~~~~~~~~~~

src/addons/withOptimizations.ts:37:7 - error TS2322: Type 'TerserPlugin' is not assignable to type '"..." | Webpa
ckPluginInstance | ((this: Compiler, compiler: Compiler) => void)'.
  Type 'TerserPlugin' is not assignable to type '(this: Compiler, compiler: Compiler) => void'.
    Type 'TerserPlugin' provides no match for the signature '(this: Compiler, compiler: Compiler): void'.

 37       new TerserPlugin({
          ~~~~~~~~~~~~~~~~~~
 38         terserOptions: {
    ~~~~~~~~~~~~~~~~~~~~~~~~
...
 80         sourceMap: shouldUseSourceMap,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 81       }),
    ~~~~~~~~

src/addons/withOptimizations.ts:83:7 - error TS2322: Type 'OptimizeCssAssetsPlugin' is not assignable to type '".
.." | WebpackPluginInstance | ((this: Compiler, compiler: Compiler) => void)'.
  Type 'OptimizeCssAssetsPlugin' is not assignable to type '(this: Compiler, compiler: Compiler) => void'.
    Type 'OptimizeCssAssetsPlugin' provides no match for the signature '(this: Compiler, compiler: Compiler): voi
d'.

 83       new OptimizeCSSAssetsPlugin({
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 84         cssProcessorOptions: {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 96         },
    ~~~~~~~~~~
 97       }),
    ~~~~~~~~

src/addons/withUnimodules.ts:3:10 - error TS2305: Module '"../../../../node_modules/webpack/types"' has no export
ed member 'ExternalsFunctionElement'.

3 import { ExternalsFunctionElement } from 'webpack';
           ~~~~~~~~~~~~~~~~~~~~~~~~

src/addons/withUnimodules.ts:97:31 - error TS2339: Property 'endsWith' does not exist on type 'string | ((pathDat
a: PathData, assetInfo?: AssetInfo | undefined) => string)'.
  Property 'endsWith' does not exist on type '(pathData: PathData, assetInfo?: AssetInfo | undefined) => string'.

97         publicUrl: publicPath.endsWith('/') ? publicPath.slice(0, -1) : publicPath,
                                 ~~~~~~~~

src/addons/withUnimodules.ts:97:58 - error TS2339: Property 'slice' does not exist on type 'string | ((pathData:
PathData, assetInfo?: AssetInfo | undefined) => string)'.
  Property 'slice' does not exist on type '(pathData: PathData, assetInfo?: AssetInfo | undefined) => string'.

97         publicUrl: publicPath.endsWith('/') ? publicPath.slice(0, -1) : publicPath,
                                                            ~~~~~

src/addons/withUnimodules.ts:124:8 - error TS2488: Type '(RuleSetRule | "...")[] | undefined' must have a '[Symbo
l.iterator]()' method that returns an iterator.

124     ...webpackConfig.module.rules,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/addons/withUnimodules.ts:188:14 - error TS7006: Parameter 'ctx' implicitly has an 'any' type.

188     return ((ctx, req, cb) => {
                 ~~~

src/addons/withUnimodules.ts:188:19 - error TS7006: Parameter 'req' implicitly has an 'any' type.

188     return ((ctx, req, cb) => {
                      ~~~

src/addons/withUnimodules.ts:188:24 - error TS7006: Parameter 'cb' implicitly has an 'any' type.

188     return ((ctx, req, cb) => {
                           ~~

src/addons/withUnimodules.ts:190:71 - error TS2554: Expected 2 arguments, but got 3.

190       return shouldIncludeModule(relPath) ? cb() : external(ctx, req, cb);
                                                                          ~~

src/addons/withWorkbox.ts:117:3 - error TS2322: Type '() => Promise<Entry>' is not assignable to type 'string | s
tring[] | EntryObject | (() => string | string[] | EntryObject | Promise<EntryStatic>) | undefined'.
  Type '() => Promise<Entry>' is not assignable to type '() => string | string[] | EntryObject | Promise<EntrySta
tic>'.
    Type 'Promise<Entry>' is not assignable to type 'string | string[] | EntryObject | Promise<EntryStatic>'.
      Type 'Promise<Entry>' is not assignable to type 'Promise<EntryStatic>'.

117   webpackConfig.entry = async () => {
      ~~~~~~~~~~~~~~~~~~~

src/addons/withWorkbox.ts:120:17 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

120     if (entries.app && !entries.app.includes(swPath) && autoRegister) {
                    ~~~

src/addons/withWorkbox.ts:120:33 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

120     if (entries.app && !entries.app.includes(swPath) && autoRegister) {
                                    ~~~

src/addons/withWorkbox.ts:133:34 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

133       if (!Array.isArray(entries.app)) {
                                     ~~~

src/addons/withWorkbox.ts:134:17 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

134         entries.app = [entries.app];
                    ~~~

src/addons/withWorkbox.ts:134:32 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

134         entries.app = [entries.app];
                                   ~~~

src/addons/withWorkbox.ts:136:15 - error TS2339: Property 'app' does not exist on type 'Entry'.
  Property 'app' does not exist on type 'string'.

136       entries.app.unshift(swPath);
                  ~~~

src/loaders/createAllLoaders.ts:2:10 - error TS2459: Module '"../../../../node_modules/webpack/types"' declares '
Rule' locally, but it is not exported.

2 import { Rule } from 'webpack';
           ~~~~

  ../../node_modules/webpack/types.d.ts:8968:6
    8968 type Rule = string | RegExp;
              ~~~~
    'Rule' is declared here.

src/loaders/createBabelLoader.ts:8:10 - error TS2459: Module '"../../../../node_modules/webpack/types"' declares
'Rule' locally, but it is not exported.

8 import { Rule } from 'webpack';
           ~~~~

  ../../node_modules/webpack/types.d.ts:8968:6
    8968 type Rule = string | RegExp;
              ~~~~
    'Rule' is declared here.

src/loaders/createFontLoader.ts:1:10 - error TS2459: Module '"../../../../node_modules/webpack/types"' declares '
Rule' locally, but it is not exported.

1 import { Rule } from 'webpack';
           ~~~~

  ../../node_modules/webpack/types.d.ts:8968:6
    8968 type Rule = string | RegExp;
              ~~~~
    'Rule' is declared here.

src/loaders/createWorkerLoader.ts:1:10 - error TS2459: Module '"../../../../node_modules/webpack/types"' declares
 'Rule' locally, but it is not exported.

1 import { Rule } from 'webpack';
           ~~~~

  ../../node_modules/webpack/types.d.ts:8968:6
    8968 type Rule = string | RegExp;
              ~~~~
    'Rule' is declared here.

src/plugins/ApplePwaWebpackPlugin.ts:3:10 - error TS2724: Module '"../../../../node_modules/webpack/types"' has n
o exported member 'compilation'. Did you mean 'Compilation'?

3 import { compilation as compilationNS, Compiler } from 'webpack';
           ~~~~~~~~~~~

src/plugins/ChromeIconsWebpackPlugin.ts:3:10 - error TS2724: Module '"../../../../node_modules/webpack/types"' ha
s no exported member 'compilation'. Did you mean 'Compilation'?

3 import { compilation as compilationNS, Compiler } from 'webpack';
           ~~~~~~~~~~~

src/plugins/ExpoDefinePlugin.ts:43:18 - error TS2702: 'OriginalDefinePlugin' only refers to a type, but is being
used as a namespace here.

43   [key: string]: OriginalDefinePlugin.CodeValueObject;
                    ~~~~~~~~~~~~~~~~~~~~

src/plugins/ExpoDefinePlugin.ts:43:18 - error TS4049: Return type of index signature from exported interface has
or is using private name 'OriginalDefinePlugin'.

43   [key: string]: OriginalDefinePlugin.CodeValueObject;
                    ~~~~~~~~~~~~~~~~~~~~

src/plugins/FaviconWebpackPlugin.ts:3:10 - error TS2724: Module '"../../../../node_modules/webpack/types"' has no
 exported member 'compilation'. Did you mean 'Compilation'?

3 import { compilation as compilationNS, Compiler } from 'webpack';
           ~~~~~~~~~~~

src/plugins/JsonWebpackPlugin.ts:2:10 - error TS2724: Module '"../../../../node_modules/webpack/types"' has no ex
ported member 'compilation'. Did you mean 'Compilation'?

2 import { compilation, Compiler } from 'webpack';
           ~~~~~~~~~~~

src/plugins/ModifyHtmlWebpackPlugin.ts:1:10 - error TS2724: Module '"../../../../node_modules/webpack/types"' has
 no exported member 'compilation'. Did you mean 'Compilation'?

1 import { compilation as compilationNS, Compiler, Plugin } from 'webpack';
           ~~~~~~~~~~~

src/plugins/ModifyHtmlWebpackPlugin.ts:1:50 - error TS2459: Module '"../../../../node_modules/webpack/types"' dec
lares 'Plugin' locally, but it is not exported.

1 import { compilation as compilationNS, Compiler, Plugin } from 'webpack';
                                                   ~~~~~~

  ../../node_modules/webpack/types.d.ts:8081:6
    8081 type Plugin =
              ~~~~~~
    'Plugin' is declared here.

src/plugins/ModifyJsonWebpackPlugin.ts:1:10 - error TS2724: Module '"../../../../node_modules/webpack/types"' has
 no exported member 'compilation'. Did you mean 'Compilation'?

1 import { compilation as compilationNS, Compiler, Plugin } from 'webpack';
           ~~~~~~~~~~~

src/plugins/ModifyJsonWebpackPlugin.ts:1:50 - error TS2459: Module '"../../../../node_modules/webpack/types"' dec
lares 'Plugin' locally, but it is not exported.

1 import { compilation as compilationNS, Compiler, Plugin } from 'webpack';
                                                   ~~~~~~

  ../../node_modules/webpack/types.d.ts:8081:6
    8081 type Plugin =
              ~~~~~~
    'Plugin' is declared here.

src/plugins/PwaManifestWebpackPlugin.ts:2:10 - error TS2724: Module '"../../../../node_modules/webpack/types"' ha
s no exported member 'compilation'. Did you mean 'Compilation'?

2 import { compilation as compilationNS, Compiler, Plugin } from 'webpack';
           ~~~~~~~~~~~

src/plugins/PwaManifestWebpackPlugin.ts:2:50 - error TS2459: Module '"../../../../node_modules/webpack/types"' de
clares 'Plugin' locally, but it is not exported.

2 import { compilation as compilationNS, Compiler, Plugin } from 'webpack';
                                                   ~~~~~~

  ../../node_modules/webpack/types.d.ts:8081:6
    8081 type Plugin =
              ~~~~~~
    'Plugin' is declared here.

src/utils/search.ts:9:3 - error TS2459: Module '"../../../../node_modules/webpack/types"' declares 'Plugin' local
ly, but it is not exported.

9   Plugin,
    ~~~~~~

  ../../node_modules/webpack/types.d.ts:8081:6
    8081 type Plugin =
              ~~~~~~
    'Plugin' is declared here.

src/utils/search.ts:10:3 - error TS2459: Module '"../../../../node_modules/webpack/types"' declares 'Rule' locall
y, but it is not exported.

10   Rule,
     ~~~~

  ../../node_modules/webpack/types.d.ts:8968:6
    8968 type Rule = string | RegExp;
              ~~~~
    'Rule' is declared here.

src/utils/search.ts:12:3 - error TS2305: Module '"../../../../node_modules/webpack/types"' has no exported member
 'RuleSetLoader'.

12   RuleSetLoader,
     ~~~~~~~~~~~~~

src/utils/search.ts:82:44 - error TS2345: Argument of type '(RuleSetRule | "...")[]' is not assignable to paramet
er of type 'RuleSetRule[]'.
  Type 'RuleSetRule | "..."' is not assignable to type 'RuleSetRule'.
    Type '"..."' has no properties in common with type 'RuleSetRule'.

82   return getRulesAsItems(getRulesFromRules(rules));
                                              ~~~~~

src/utils/search.ts:93:58 - error TS2345: Argument of type '(RuleSetRule | "...")[]' is not assignable to paramet
er of type 'RuleSetRule[]'.

93   const currentRules = getRulesAsItems(getRulesFromRules(rules));
                                                            ~~~~~

src/utils/search.ts:135:46 - error TS2551: Property 'loaders' does not exist on type 'RuleSetRule'. Did you mean
'loader'?

135     return loaderToLoaderItemLoaderPart(rule.loaders || rule.loader || rule.use).map(loader => ({
                                                 ~~~~~~~

  ../../node_modules/webpack/types.d.ts:9203:2
    9203  loader?: string;
          ~~~~~~
    'loader' is declared here.

src/utils/search.ts:159:57 - error TS2345: Argument of type '{}' is not assignable to parameter of type '{ resour
ce: string; realResource: string; resourceQuery: string; issuer: string; compiler: string; }'.
  Type '{}' is missing the following properties from type '{ resource: string; realResource: string; resourceQuer
y: string; issuer: string; compiler: string; }': resource, realResource, resourceQuery, issuer, compiler

159     loaders.push(...loaderToLoaderItemLoaderPart(loader({})));
                                                            ~~

src/utils/search.ts:214:30 - error TS2349: This expression is not callable.
  Type 'never' has no call signatures.

214     return resolveRuleSetUse(rule({}));
                                 ~~~~

src/webpack.config.ts:23:62 - error TS2305: Module '"../../../node_modules/webpack/types"' has no exported member
 'Options'.

23 import webpack, { Configuration, HotModuleReplacementPlugin, Options, Output } from 'webpack';
                                                                ~~~~~~~

src/webpack.config.ts:23:71 - error TS2459: Module '"../../../node_modules/webpack/types"' declares 'Output' loca
lly, but it is not exported.

23 import webpack, { Configuration, HotModuleReplacementPlugin, Options, Output } from 'webpack';
                                                                         ~~~~~~

  ../../node_modules/webpack/types.d.ts:7458:19
    7458 declare interface Output {
                           ~~~~~~
    'Output' is declared here.

src/webpack.config.ts:107:21 - error TS2694: Namespace 'exports' has no exported member 'DevtoolModuleFilenameTem
plateInfo'.

107       info: webpack.DevtoolModuleFilenameTemplateInfo
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/webpack.config.ts:120:21 - error TS2694: Namespace 'exports' has no exported member 'DevtoolModuleFilenameTem
plateInfo'.

120       info: webpack.DevtoolModuleFilenameTemplateInfo
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/webpack.config.ts:362:46 - error TS2345: Argument of type 'typeof HtmlWebpackPlugin' is not assignable to par
ameter of type 'HtmlWebpackPlugin'.
  Property 'userOptions' is missing in type 'typeof HtmlWebpackPlugin' but required in type 'HtmlWebpackPlugin'.

362       ExpoInterpolateHtmlPlugin.fromEnv(env, ExpoHtmlWebpackPlugin),
                                                 ~~~~~~~~~~~~~~~~~~~~~

  ../../node_modules/html-webpack-plugin/typings.d.ts:10:3
    10   userOptions: HtmlWebpackPlugin.Options;
         ~~~~~~~~~~~
    'userOptions' is declared here.
  src/webpack.config.ts:362:46
    362       ExpoInterpolateHtmlPlugin.fromEnv(env, ExpoHtmlWebpackPlugin),
                                                     ~~~~~~~~~~~~~~~~~~~~~
    Did you mean to use 'new' with this expression?


Found 54 errors.
```


Add any casting to 

- [ ] src/addons/withUnimodules.ts:93
- [ ] src/addons/withUnimodules.ts:123
- [ ] src/addons/withUnimodules.ts:192
- [ ] src/addons/withUnimodules.ts:187
- [ ] src/addons/withEntry.ts:40
- [ ] src/addons/withNodeMocks.ts:19
- [ ] src/addons/withOptimizations.ts:98
- [ ] src/addons/withWorkbox.ts:118
- [ ] src/loaders/createAllLoaders.ts:9
- [ ] src/loaders/createBabelLoader.ts:12
- [ ] src/loaders/createFontLoader.ts:1
- [ ] src/loaders/createWorkerLoader.ts:1
- [ ] src/plugins/ApplePwaWebpackPlugin.ts:32
- [ ] src/plugins/ApplePwaWebpackPlugin.ts:30
- [ ] src/plugins/ExpoDefinePlugin.ts:43
- [ ] src/plugins/FaviconWebpackPlugin.ts:23
- [ ] src/plugins/JsonWebpackPlugin.ts:42
- [ ] src/plugins/ModifyHtmlWebpackPlugin.ts:3
- [ ] src/plugins/ModifyHtmlWebpackPlugin.ts:30
- [ ] src/plugins/ModifyHtmlWebpackPlugin.ts:39
- [ ] src/plugins/ModifyJsonWebpackPlugin.ts:11
- [ ] src/plugins/ModifyJsonWebpackPlugin.ts:20
- [ ] src/plugins/PwaManifestWebpackPlugin.ts:13
- [ ] src/plugins/PwaManifestWebpackPlugin.ts:40
- [ ] src/plugins/JsonWebpackPlugin:12
- [ ] src/plugins/JsonWebpackPlugin:22
- [ ] src/plugins/JsonWebpackPlugin
- [ ] src/utils/search.ts:26
- [ ] src/utils/search.ts:29
- [ ] src/utils/search.ts:51
- [ ] src/utils/search.ts:79
- [ ] src/utils/search.ts:88
- [ ] src/utils/search.ts:90
- [ ] src/utils/search.ts:132
- [ ] src/utils/search.ts:158
- [ ] src/utils/search.ts:213
- [ ]  src/utils/search.ts:298
- [ ] src/webpack.config.ts:68
- [ ] src/webpack.config.ts:69
- [ ] src/webpack.config.ts:89
- [ ] src/webpack.config.ts:90
- [ ] src/webpack.config.ts:107
- [ ] src/webpack.config.ts:120
- [ ] src/webpack.config.ts:180
- [ ] src/webpack.config.ts:360

**Comment by marklawlor** [comment]
Created a blank slate that successfully compiles react-native-web. Now I need to enabled the Expo features
